### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by StephLin** [OpenMCL/ziyou-python-write-ups#4]
We need to set milestones so that the project can be tracked properly.

⚠️ Followings are draft!

## :calendar: Important Dates

- `2022.12.31`: Release `alpha`. 
- `2023.02.12`: Release `v0.9.0`.
- `2023.04.30`: Release `v1.0.0rc1` (the first release candidate of `v1.0.0`).
- `2023.06.30`: Release `v1.0.0`.

## ✅ Milestone of `alpha` (Done)

- [x] Setup environments to align developers' coding styles and writing styles.

## 🟡 Milestone of `v0.9.0` (In Progress)

無詳解版本的解答集。

- [ ] 完成所有題目
- [x] 修正程式碼格式問題
- [ ] Close the milestone tracker [#5](https://github.com/OpenMCL/ziyou-python-write-ups/issues/5)

## ⚫ Milestone of `v1.0.0rc1` (Todo)

有詳解的解答集初版。

- [ ] 確認程式碼執行結果無誤
- [ ] 初步修正程式碼易讀性問題
- [ ] 制定統一詳解格式
- [ ] 此版本亦需要提交給文秀做校對、提交給國師供參考

## ⚫ Milestone of `v1.0.0` (Todo)

第一個正式對外發布的版本。

- [ ] 文秀完成校對並修正
- [ ] 提升程式碼可讀性
- [ ] 國師最終確認、封版、並完成發布工作。
