### ISSUE TITLE
Plan for v0.9.0

### ISSUE THREAD

**Issue by StephLin** [OpenMCL/ziyou-python-write-ups#5]
This plan captures all works for v0.9.0. The major objective of this version is to provide simplified solution of all questions, with valid coding styles.

## Action Items

| Mark | Description |
| ---- | ----------- |
| 🏃 | work in progress |
| 👁️‍🗨️ | under review |
| ✋ | blocked task |
| 🔴 | missing doer |
| ⚫ | under discussion |

### Code

- [ ] Finish all questions [#1](https://github.com/OpenMCL/ziyou-python-write-ups/issues/1)
  - [x] Finish questions of chapters 3 and 4 [#9](https://github.com/OpenMCL/ziyou-python-write-ups/pull/9) [#10](https://github.com/OpenMCL/ziyou-python-write-ups/pull/10) @StephLin
  - [ ] 🔴 Finish questions of chapter 5
  - [ ] 🔴 Finish questions of chapter 6
- [x] Resolve linting issues of all Python code [#2](https://github.com/OpenMCL/ziyou-python-write-ups/issues/2) @StephLin
- [x] Unify input format [#6](https://github.com/OpenMCL/ziyou-python-write-ups/pull/6) @StephLin 
- [ ] ⚫ Unit test / integrated test for python implementations

### Tex Document

- [x] Prevent ambiguous header [#7](https://github.com/OpenMCL/ziyou-python-write-ups/pull/7) @StephLin

### Dev Document

- [x] Write down environment setup guide for programming [#8](https://github.com/OpenMCL/ziyou-python-write-ups/pull/8) @StephLin
